// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package store

import (
	"database/sql"
	"time"
)

type RoachMigration struct {
	ID         string
	Key        string
	Filename   string
	Completed  bool
	Failed     bool
	FailReason sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
